audit_header: false
title: -- MARKET -- Real Estate Video Blog with -- CLIENT NAME --
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Robin Phillips
  title:
  license_number:
  about_markdown: |
    I provide a superior level of service to successful people with passion and purpose, so they can experience the extraordinary lifestyle they so richly deserve!

    Graduating from university with degrees in Finance, Accounting and a minor in international business, Robin took a corporate job at the age of 22 with big ambitions! She lived in Germany & Sweden and worked in Mexico in her first 3 years.

    Every year for 10 years, Robin’s family vacationed in the Bahamas. As if by kismet, one year Robin met David. He and his family owned the resort Robin visited. After a year on the phone and two weeks in person, they were engaged! For the next 16 years Robin & David owned & managed the resort across the harbor, the Bluff House Beach Resort & Marina on Green Turtle Cay, Abaco, Bahamas. Four massive hurricanes hit that small island during their time there, the worst was Hurricane Floyd, a category 5 storm that destroyed every building. After a short 11 months, the team had rebuilt the resort, all while Robin had her first son William, born only 3 weeks after the hurricane hit the island.

    Adventurous. Resilient. Determined. Driven. Robin & David sold the resort at the bottom of the market in 2009 & left the island in 2012, because their two children needed a better education. They chose Charleston for the Academic Magnet school. Little did they know that their son, William, was autistic.

    Arriving in Charleston with little money, no credit, and no marketable skills, it was challenging! Knowing they could run a business, Robin & David decided to get their real estate licenses. They had developed and sold real estate in the Bahamas, so it seemed a natural fit! Only a few years later, Robin has sold nearly $65 Million dollars of real estate without a team, and while fighting breast cancer.

    Her specialty is hard to sell homes, unique homes, or those that sit on the market too long. With her finance background, she also loves to help investors or second homeowners. Her passion for education and helping others stems from her two parents. She is driven to educate, support and grow those around her.

    No one is more serious about seeing her clients experience the lifestyle they so richly deserve, and every extraordinary adventure that comes with it
  brand: The Robin Group
  brokerage: eXp Realty
  market:
  address: 170 Meeting St, STE 304, Charleston, SC 29401
  phone: 843.214.8451
  phone_type:
  phone2:
  phone2_type:
  email: Robin@FindYourPerfectNest.com
  url: http://experiencetheextraordinary.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://robinphillips.exprealty.com/sell.php
  second_CTA_text: Home Search
  second_CTA_URL: https://robinphillips.exprealty.com/index.php?rtype=grid

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://robinphillips.exprealty.com/sell.php

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://robinphillips.exprealty.com/index.php?rtype=grid

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/RobinPhillipsEXP
  linkedin_url: https://www.linkedin.com/in/charlestonhomevalues
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Your Realtor Robin. Teaching you to buy & sell like an expert!
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#d9c4b1'
  theme_color: '#31394c'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
